# Introduction to Python language

## Reusing code: script and modules

### Code snippet

<div class="alert alert-success">

<b>EXERCISE</b>:

Write a code snippet which will split a sentence into several words and print each word.

</div>

In [1]:
msg = 'Hi, welcome to Euroscipy.'

msg.split()

['Hi,', 'welcome', 'to', 'Euroscipy.']

In [2]:
for word in msg.split():
    print(word)

Hi,
welcome
to
Euroscipy.


<div class="alert alert-success">

<b>EXERCISE</b>:

Move this script inside a file `welcome_message.py` and run it throw the command line.

</div>

### import syntax

In [3]:
import numpy

numpy.random.random((2, 2))

array([[ 0.74375128,  0.64450871],
       [ 0.17244684,  0.02288068]])

In [4]:
import numpy as np

np.random.random((2, 2))

array([[ 0.54175615,  0.91738485],
       [ 0.75774886,  0.92515434]])

In [5]:
from numpy import random

random.random((2, 2))

array([[ 0.16813354,  0.93369973],
       [ 0.85557145,  0.95085602]])

In [6]:
from numpy.random import random as rnd_mat

rnd_mat((2, 2))

array([[ 0.34884977,  0.14467685],
       [ 0.7808681 ,  0.27365402]])

<div class="alert alert-success">

<b>EXERCISE</b>:

Create a module `operators.py` including 2 functions: `addition` and `subtraction` which add and subtract two numbers.

Create a main file importing the 2 functions from operators and call them with some examples.

</div>

<div class="alert alert-info">

<b>DEMO</b>:

Demo using `sys` argument.

</div>